# Generated by Django 5.2 on 2025-04-10 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vet',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='vet_photos/'),
        ),
    ]
