# Generated by Django 5.2 on 2025-05-09 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_alter_vet_phone_number_delete_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='vet',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
