# Generated by Django 5.2 on 2025-05-13 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0007_alter_appointment_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название услуги')),
                ('description', models.TextField(verbose_name='Описание')),
                ('icon', models.CharField(help_text='Название иконки из Font Awesome', max_length=50, verbose_name='Иконка')),
                ('color', models.CharField(default='#4169E1', max_length=20, verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
    ]
