# Generated by Django 5.2 on 2025-05-13 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0008_service'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
