# Generated by Django 5.2 on 2025-06-09 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0015_chat_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='has_unread_messages',
            field=models.BooleanField(default=False),
        ),
    ]
